### PR TITLE
Update PersistentCollectionSerializer.java

### PR DESCRIPTION
**Pull request by Taha-Di-Nero**
fix REPLACE_PERSISTENT_COLLECTIONS in EAGER #146

### CODE REVIEW

**Comment by pjfanning** [comment]
@cowtowncoder I am not a lawyer - but this PR seems to be a direct copy of #140 so this PR should not be consider the original work of @Taha-Di-Nero - this make it problematic to merge this PR since the copyright on the code here is at least debatable.

**Comment by cowtowncoder** [comment]
We'd also need this for all backends, not just H5 and H6.

But as to contribution, this is not a super sizable change so one could argue either way I suppose.
Let me ping original author on $146 once more.

**Comment by Taha-Di-Nero** [comment]
@pjfanning @cowtowncoder  Yes this is applying the same patch done in https://github.com/FasterXML/jackson-datatype-hibernate/pull/146 but for hibernate 6, the author of https://github.com/FasterXML/jackson-datatype-hibernate/pull/146 is my collegue and I asked him to do what @cowtowncoder  requested but he doesn't want to do it.
We need only hibernate 6 and we manage it via a small fork that we would like to remove.
Best regards

**Comment by cowtowncoder** [comment]
@Taha-Di-Nero Ok as long as author is fine with your contributing the code (you have discussed it), and you are ok sending CLA (which just attests that you think you can contribute the code), I think we can merge it.

But one thing I realize now is that there is no unit test to verify this fix works. I guess you are using a fork so I don't doubt it doesn't, but if there was one way to test it that'd obviously be great.

**Comment by Taha-Di-Nero** [comment]
[contributor-agreement.pdf](https://github.com/FasterXML/jackson-datatype-hibernate/files/11556405/contributor-agreement.pdf)
Hi
Unfortunately we don't implement any tests.
Best regards

**Comment by cowtowncoder** [comment]
Excellent, thank you @Taha-Di-Nero ! Ok, aside from tests (it's ok since you have tested this), could I ask same changes for `hibernate5` and `hibernate5-jakarta` modules? :)

If you don't have time I can do it later on but just in case. I hope to merge this later today -- thank you once again for contributing this.

**Review by cowtowncoder — APPROVED** [review]

**Pull request merged**
