### PR TITLE
Fix issue #111

### PR DESCRIPTION
**Pull request by mdahm**
https://github.com/FasterXML/jackson-datatype-hibernate/issues/111

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thank you for the contribution!

Could you add some notes on how this resolves the issue, and whether it would work across 5.x versions, or just particular one(s)? (5.2?). The reason I am asking is that my understanding has been that there are problems in trying to get module working across Hibernate 5.x minor versions.

**Comment by mdahm** [comment]
Nothing to thank for. That bug really annoyed me :-)

Well, as you probably have noticed I tried to make the code behave more defensively.
The old solution worked for Hibernate 5.0. As far as I know the API change that broke the code came with version 5.1. Currently I'm working with WildFly 13 which has Hibernate core 5.3 built in.
So we should be safe here...

The check for the EntityManager uses a documented API so that should be OK:

https://docs.oracle.com/javaee/7/api/javax/persistence/EntityManager.html#getTransaction--

The second check merely uses the fact that Hibenate will instantiate a specific coordinator class if running in a JTA environment. That might work as well in all 5.x versions, but I haven' tried.

**Comment by mdahm** [comment]
BTW you should forget/rollback the second commit that was unintentionally...

**Comment by cowtowncoder** [comment]
@mdahm Thank you for explanation. I can probably test it myself. And although it would be safer to defer this to 2.10, I think I'll merge it for `2.9` [.7] as otherwise this module just isn't that usable.

**Pull request merged**
