### PR TITLE
fix REPLACE_PERSISTENT_COLLECTIONS in EAGER 

### PR DESCRIPTION
**Pull request by pses**
issue https://github.com/FasterXML/jackson-datatype-hibernate/issues/140

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Apologies for slow follow up here.

Looks good in general, thank you very much for submitting it!

Couple of small things:

1. Would it make sense to add this in 2.13 branch, to be included in 2.13.2 (`master` is for upcoming 2.14.0)
2. There are 3 modules (hibernate4, hibernate5, hibernate5-jakarta), so changes need to be added to the other 2

It would also be great to have a reproduction (unit test), although I don't know how easy it'd be to create one.

Also: once this is ready for merge to the right branch, I would need a CLA (unless I have received one before -- if you have sent one let me know). It's here:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and the usual way is to print the 1-page doc, fill & sign it, scan/take photo, email to `info` at fasterxml dot com.
Once I receive it I can merge PR and CLA is good for any other contributions as well (so it's one time thing before the first contribution).

**Comment by cowtowncoder** [comment]
Would still be great to get this in....

**Comment by pjfanning** [comment]
@pses would you be interested in still getting this merged? If not, would be willing to put this code in the public domain so other users could work on getting it merged? For context, see #173.

**Comment by cowtowncoder** [comment]
Replaced by #173, closing.

**Pull request closed without merging**
